[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "git+https://github.com/cython/cython",
]
build-backend = "setuptools.build_meta"

[project]
name = "adder"
version = "0.0.1"
dynamic = ["requires-python"]

[tool.setuptools_scm]

[tool.setuptools]
packages = ["adder"]
